# Generated by Django 5.2.5 on 2025-08-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="secret_token",
            field=models.CharField(
                default="cb85758225fcd5c80bfd6b9a6d1ef51f", max_length=100, unique=True
            ),
        ),
    ]
