# Generated by Django 5.2.5 on 2025-11-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_secret_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='secret_token',
            field=models.CharField(default='3b6ed268c4eec10643cf109bea415bcc', max_length=100, unique=True),
        ),
    ]
